
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# webcam nexus7
android_ip_webcam:
  - name: "NAME"
    host: IP
    port: 8080
    username: 'USER'
    password: 'PASS'
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - sound
      - video_connections
    switches:
      - motion_detect
      - overlay
      - video_recording

