

version: '3'
services:
  hass:
    image: homeassistant/home-assistant
    restart: always
    network_mode: host
    ports:
      - 8123:8123
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCC7EC1-if00:/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCC7EC1-if00
    volumes:
      - ./:/config
      - "/etc/localtime:/etc/localtime:ro"

